### ISSUE TITLE
Web Demo is not working

### ISSUE THREAD

**Issue by ghpkishore** [Lakonik/MVEdit#1]
Hi! The webdemo link in the https://lakonik.github.io/mvedit/ isnt working

**Comment by Lakonik** [comment]
Hi! Thank you for your feedback, can you provide more information? Do you have connection problems or do you encounter errors during generation?

Best regards,
Hansheng

Sent from Mail for Windows

From: Garimella Hari Pawan Kishore
Sent: Monday, March 18, 2024 10:03 PM
To: Lakonik/MVEdit
Cc: Subscribed
Subject: [Lakonik/MVEdit] Web Demo is not working (Issue #1)

Hi! The webdemo link in the https://lakonik.github.io/mvedit/ isnt working

**Comment by ghpkishore** [comment]
The url wasnt connecting.  hjad tried in different devices and networks but still couldnt connect. It is working fine now. Closing ticket
