### ISSUE TITLE
image to gaussians

### ISSUE THREAD

**Issue by Dumeowmeow** [Lakonik/MVEdit#18]
Hi, thank you for your great work!
May I ask where is the code for image to 3dgaussians in 3DAdapter?

**Comment by Lakonik** [comment]
Thank you for your interest in our work!
Our Gaussian-related code is built upon [GRM](https://github.com/justimyhxu/GRM), which is currently unavailable for some reason. Unfortunately, I don't think we can release our copy of GRM before their official release, so we'll have to wait for that first.

**Comment by Dumeowmeow** [comment]
> Thank you for your interest in our work! Our Gaussian-related code is built upon [GRM](https://github.com/justimyhxu/GRM), which is currently unavailable for some reason. Unfortunately, I don't think we can release our copy of GRM before their official release, so we'll have to wait for that first.

I know.Thank you for your reply!

**Comment by Dumeowmeow** [comment]
> Thank you for your interest in our work! Our Gaussian-related code is built upon [GRM](https://github.com/justimyhxu/GRM), which is currently unavailable for some reason. Unfortunately, I don't think we can release our copy of GRM before their official release, so we'll have to wait for that first.

Sorry, I have another question.When I get the mesh, I tried to render it in the original view: camera_poses[0]
https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L696
But I found it was not the same as the original picture.
 
rendered image:
![image](https://github.com/user-attachments/assets/9e33012e-26bb-49b9-aa46-ecc96d512a4c)
original image:
![car_whitebg](https://github.com/user-attachments/assets/d970c88e-f0d3-4b5e-9520-8f052c125b36)
Their Angle appears obvious offset, excuse me this is normal, how should solve?

**Comment by Lakonik** [comment]
Both the GRM Adapter and MVEdit Adapter adopt Zero123++ as the multi-view model. Since Zero123++ automatically aligns the output with the gravity axis, the elevation angle of the input is ignored.

I assume you are using the MVEdit Adapter. If so, MVEdit does have an internal estimation of the elevation angle:
https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L807-L813

You can modify the code so that the estimated pose is returned.

**Comment by Dumeowmeow** [comment]
> Both the GRM Adapter and MVEdit Adapter adopt Zero123++ as the multi-view model. Since Zero123++ automatically aligns the output with the gravity axis, the elevation angle of the input is ignored.
> 
> I assume you are using the MVEdit Adapter. If so, MVEdit does have an internal estimation of the elevation angle:
> 
> https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L807-L813
> 
> You can modify the code so that the estimated pose is returned.

Thank you for your reply! I got it. And, another question is, if my input image is 512x512, How can I make mesh render 512x512 with the same scale as the original image?I found that there were a lot of image sizing operations in the code that confused me.

**Comment by Dumeowmeow** [comment]
> > Both the GRM Adapter and MVEdit Adapter adopt Zero123++ as the multi-view model. Since Zero123++ automatically aligns the output with the gravity axis, the elevation angle of the input is ignored.
> > I assume you are using the MVEdit Adapter. If so, MVEdit does have an internal estimation of the elevation angle:
> > https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L807-L813
> > 
> > You can modify the code so that the estimated pose is returned.
> 
> Thank you for your reply! I got it. And, another question is, if my input image is 512x512, How can I make mesh render 512x512 with the same scale as the original image?I found that there were a lot of image sizing operations in the code that confused me.

I tried to render the resulting mesh with the following parameters and output a 288x288 image, but its scale is not the same as the 288x288 image sent to the model：
https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L792-L804

the 288x288 image fed to mveditpipeline in https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L790
![image](https://github.com/user-attachments/assets/11697c93-d5c6-4586-a072-63f1f198489a)
the image rendered from the resulting mesh using the parameters in the above parameters:
![image](https://github.com/user-attachments/assets/511be96e-f8b3-44a4-a08b-adbe0b183890)
It looked as if it had grown bigger.Is there something wrong with my camera Settings?I expect their results to be the same.

**Comment by Dumeowmeow** [comment]
> > > Both the GRM Adapter and MVEdit Adapter adopt Zero123++ as the multi-view model. Since Zero123++ automatically aligns the output with the gravity axis, the elevation angle of the input is ignored.
> > > I assume you are using the MVEdit Adapter. If so, MVEdit does have an internal estimation of the elevation angle:
> > > https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L807-L813
> > > 
> > > You can modify the code so that the estimated pose is returned.
> > 
> > 
> > Thank you for your reply! I got it. And, another question is, if my input image is 512x512, How can I make mesh render 512x512 with the same scale as the original image?I found that there were a lot of image sizing operations in the code that confused me.
> 
> I tried to render the resulting mesh with the following parameters and output a 288x288 image, but its scale is not the same as the 288x288 image sent to the model：
> 
> https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L792-L804
> 
> the 288x288 image fed to mveditpipeline in
> 
> https://github.com/Lakonik/MVEdit/blob/445a11c0e0e38a581f94df57af48357bd1c5cd47/lib/apis/adapter3d.py#L790
> 
> 
> ![image](https://private-user-images.githubusercontent.com/99797884/384017754-11697c93-d5c6-4586-a072-63f1f198489a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDQ3MzUsIm5iZiI6MTczMTMwNDQzNSwicGF0aCI6Ii85OTc5Nzg4NC8zODQwMTc3NTQtMTE2OTdjOTMtZDVjNi00NTg2LWEwNzItNjNmMWYxOTg0ODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA1NTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzhhZDkyODZjMDIxODJlNGE3MDg4YThkYzA1NTI2ZjE3ZjkyZDliNDY4ZjUzMzI2ZjNmYmI0NjNhZjU4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HsIH5eBGVs4VMuPO6z057Ucztkb89yxYfFgKnAGvJVA)
> the image rendered from the resulting mesh using the parameters in the above parameters:
> ![image](https://private-user-images.githubusercontent.com/99797884/384018056-511be96e-f8b3-44a4-a08b-adbe0b183890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDQ3MzUsIm5iZiI6MTczMTMwNDQzNSwicGF0aCI6Ii85OTc5Nzg4NC8zODQwMTgwNTYtNTExYmU5NmUtZjhiMy00NGE0LWEwOGItYWRiZTBiMTgzODkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA1NTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YmU3OTllMDFjNDkyOGI3MjIwNGQ5YmVkMTg4NmUyMzZiZWM1MmM5Yzg3ZWMwZmQ2YjFiOGUwNzRjNjEyMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vTjgdrGfVN7zWMaanFEtrC3DSgYedig56v1CdjWnYkg)
> It looked as if it had grown bigger.Is there something wrong with my camera Settings?I expect their results to be the same.

Is this due to up and down sampling of the network?
