### ISSUE TITLE
CLI Runtime

### ISSUE THREAD

**Issue by jclarkk** [Lakonik/MVEdit#4]
Hey guys,

Really loving this project so far, lots of tools to play around with which is always fun!

Any chance for a straightforward way to run some pipelines via CLI? Would be greatly appreciated.

**Comment by Lakonik** [comment]
Hi! Thanks for your interest in our work. Usually we recommend using the APIs provided by the Gradio demo as described in README.md. We will also add some example python scripts to show the direct usage of the pipelines, but this may not cover all the functionalities in the Web UI.

**Comment by jclarkk** [comment]
Thanks for the explanation!
