### ISSUE TITLE
Top and bottom views

### ISSUE THREAD

**Issue by jclarkk** [Lakonik/MVEdit#5]
Due to the limited vertical angles when using Zero123 the top and bottom views can suffer in both the mesh and the texture.

Bad texture example:
![image](https://github.com/Lakonik/MVEdit/assets/6411191/0363e61c-30b8-44b6-b3b4-90f3646e4a55)

Bad mesh example:
![image](https://github.com/Lakonik/MVEdit/assets/6411191/bf2dc4fc-b7f7-4d78-bdb4-cb9b6557c895)

Would it be possible to have more control via the UI?

Thanks!

**Comment by Lakonik** [comment]
Hi! Unfortunately I don't think there's an easy way to fix the top and bottom views perfectly. SD models themselves are not quite good at generating these views. 

One way that might improve the top view texture is to increase the max elevation angle here (in radians):
https://github.com/Lakonik/MVEdit/blob/9f01b211bfd6b30b4aa5583ad73727c46c2c31db/lib/apis/mvedit.py#L114

**Comment by jclarkk** [comment]
Thanks for the tip!
