### ISSUE TITLE
The web demo isn't working

### ISSUE THREAD

**Issue by SBlumenstock1** [Lakonik/MVEdit#6]
Hi there! Nice work but the [web demo](https://lakonik.github.io/mvedit_demo/) is not working anymore.
I get this error: 

`upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection termination`
`Failed to load resource: the server responded with a status of 503 ()`

**Comment by Lakonik** [comment]
Hi! Thanks for your feedback. We are fixing some hardware issues right now. Hopefully the web demo will be brought back in a few days.

**Comment by Lakonik** [comment]
The demo is back online now
